# Generated by Django 4.0.1 on 2022-02-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_speaker_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='role',
            field=models.CharField(choices=[('speaker', 'speaker'), ('mentor', 'mentor')], default='speaker', max_length=200),
        ),
    ]
