# Generated by Django 4.0.1 on 2022-01-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('diamond', 'DIMOND'), ('platinum', 'PLAINUM'), ('gold', 'GOLD'), ('silver', 'SILVER'), ('bronze', 'BRONZE')], default='diamond', max_length=20)),
            ],
        ),
    ]
