# Generated by Django 4.0.1 on 2022-01-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebok',
            new_name='facebook',
        ),
    ]
