# Generated by Django 4.0.1 on 2022-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_facebok_team_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, max_length=1050),
        ),
    ]
