# Generated by Django 4.0.1 on 2022-02-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='domain',
            field=models.CharField(choices=[('lead', 'lead'), ('web', 'web'), ('documentation', 'documentation'), ('design', 'design'), ('sponsership', 'sponsership')], default='web', max_length=200),
        ),
    ]
