# Generated by Django 4.0.1 on 2022-02-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.CharField(max_length=2000),
        ),
    ]
