# Generated by Django 4.0.1 on 2022-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=1050)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
